config/routes.rb
Rails.application.routes.draw do

  get "about" => 'static_pages#about'
  get "login" => 'sessions#new'
  post "login" => 'sessions#create'
  delete "logout" => 'sessions#destroy'

  resources :users
  resources :tweets, only: [:create, :destroy]

  root 'static_pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
has_and_belongs_to_many :tweets

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  mount_uploader :picture, PictureUploader
  default_scope -> { order(created_at: :desc) }
  has_many :comments
  has_and_belongs_to_many :tags
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :picture_size

  private
  #validates the size of an uploader picture
  def picture_size
    if picture.size > 2.megabytes
      errors.add(:picture, "should be less than 2MB")
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, length: { minimum: 6}, allow_blank: true
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /[\w+\-.]+@[a-z\.]+\.[a-z]+/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }


  has_many :tweets, dependent: :destroy
  has_many :comments
  before_save :set_handle

  def feed
    Tweet.where("user_id = ?", id)
  end

  private

  def set_handle
    self.handle ||= email
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  #Confirms a logged-in user
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
       @tweet = current_user.tweets.build
       @feed_items = current_user.feed.paginate(page: params[:page]).per_page(10)
    end
  end

  def about
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
before_action :logged_in_user, only: [:create, :destroy]
before_action :correct_user, only: :destroy
  def create
    @tweet = current_user.tweets.build(tweet_params)
      if @tweet.save
        flash[:success] = "Tweet created!"
        redirect_to root_url
      else
        @feed_items = []
        render 'static_pages/home'
      end
  end

  def destroy
    @tweet.destroy
    flash[:success] = "Tweet deleted"
    redirect_to request.referrer
  end

  private

    def tweet_params
      params.require(:tweet).permit(:content, :picture)
    end

    def correct_user
      @tweet = current_user.tweets.find_by(id: params[:id])
      redirect_to root_url if @tweet.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page]).per_page(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:info] = "Welcome to InstaTweet"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.paginate(page: params[:page]).per_page(10)
    @tweet = current_user.tweets.build if logged_in?
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :handle, :statement)
  end

  #confirms a logged in user
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  #confirms correct user
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  #confirms admin
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end


  #Returns the current logged-in user (if any)
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end

  #Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end


  #Redirects back to stored location (or back to user by default)
  def redirect_back_or(user)
    redirect_to(session[:forwarding_url] || user)
    session.delete(:forwarding_url)
  end

  #Stores the URL trying to get to.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end


  def current_user?(user)
    user == current_user
  end


  #logs out user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end





end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.handle, class: "gravatar")
  end


end

app/views/layouts/_footer.html.erb
<footer class="footer">
 <ul class="nav navbar-nav">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
    <% else %>
      <li><%= link_to "Login", login_path %></li>
    <% end %>
    </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-top navbar-inverse" id="topnav">
  <div class="nav_container">
   <nav class="navbar navbar-expand-lg">
    <a class="navbar-brand logo" href='/'>
    InstaTweet
    </a>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log Out", logout_path, method: "delete" %>
                  </li>
                </ul>
            </li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title><%= full_title(yield(:title)) %> | InstaTweet</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>" id ="body"><%= message %></div>
    <% end %>
    <%= yield %>
  <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class='tweets'>
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
  <% end %>

app/views/shared/_tweet_form.html.erb
<%= form_for(@tweet) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Tweet away", rows: 10, class: "form-control textarea" %>
  </div>
    <%= f.submit "Post", class: "btn btn-primary form-control" %>
    <span class="picture">
      <%= f.file_field :picture, accept: "image/jpeg, image/gif, image.png" %>
    </span>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 120), current_user %>
<h1 class="profile"><%= current_user.handle %></h1>
<span><%= link_to "View my profile", current_user %></span> |
<span><%= pluralize(current_user.tweets.count, "tweet") %> </span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron" id='bgmain'>
<h1>About InstaTweet</h1>
<h3>
  InstaTweet is a social media sharing app that provides real time tweets with photos and videos.
</h3>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-md-4">
      <div class="user-info">
        <%= render 'shared/user_info' %>
      </div>
      <div class="tweet_form">
        <%= render 'shared/tweet_form' %>
      </div>
    </div>
    <div class="col-md-7">
      <h3>Tweets Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>

<% else %>
<div class="center jumbotron" id='bgmain'>
  <h1 class="homepage">Welcome to InstaTweet</h1>
  <h2 class="homepage">
      InstaTweet is a social media sharing app that provides real time
      tweets with photos and videos.
  </h2>
  <p>
      <%= link_to "Sign Up", new_user_path, class: "btn btn-lg btn-success" %>
  </p>

</div>

<% end %>

app/views/tweets/_tweet.html.erb
<li id="tweet-<%= tweet.id %>">
  <%= link_to gravatar_for(tweet.user, size: 50), tweet.user %>
  <span class="user"><%= link_to tweet.user.handle, tweet.user %></span>
  <span class="content">
  <%= tweet.content %> |
  <span class="timestamp">
    Posted <%= time_ago_in_words(tweet.created_at) %> ago.
    <% if current_user?(tweet.user) %>
      <%= link_to "delete", tweet, method: :delete,
                                      data: { confirm: "You sure?" } %>
    <% end %>
  </span>
  <%= image_tag tweet.picture.url if tweet.picture? %>
  </span>
  </li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :handle %>
      <%= f.text_field :handle, class: 'form-control' %>

      <%= f.label :statement, "About Me" %>
      <%= f.text_field :statement, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save Changes", class: "btn btn-primary form-control" %>
    <% end %>

    <div class="gravatar">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
  <li>
    <%= link_to gravatar_for(user, size: 100), user %>
    <%= link_to user.handle, user, class: 'text' %>
    <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% end %>
  </li>
  <% end %>
</ul>

<%= page_entries_info @users %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <%= form_for @user do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :handle %>
      <%= f.text_field :handle, class: 'form-control' %>

      <%= f.label :statement, "About Me" %>
      <%= f.text_field :statement, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password,class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create Account", class: "btn btn-primary submit-button" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.handle) %>
<div class="row">
  <aside class="col-md-4 ">
    <section class="user_info">
      <%= gravatar_for @user, size: 120; %>
      <h1 class="profile">
      <%= @user.handle %>
      </h1>
    </section>
    <% if @user == current_user %>
      <%= form_for(@tweet) do |f| %>
        <div class="field">
      <%= f.text_area :content, placeholder: "Tweet away", rows: 10, class: "form-control textarea" %>
        </div>
      <%= f.submit "Post", class: "btn btn-primary" %>
      <% end %>
    <% end %>
      <h5> About Me </h5>
      <p> <%= @user.statement %> </p>
  </aside>
  <div class="col-md-8">
  <% if @user.tweets.any? %>
    <h3>Tweets (<%= @user.tweets.count %>)</h3>
    <%= will_paginate @tweets %>
    <ol class="tweets">
      <%= render @tweets %>
    </ol>
    <%= page_entries_info @tweets %>
  <% end %>
  </div>